sysstat/sysstat

configure.in
Now, when the sa2 script fully supports xz files, let's use them by default when
compressing sa data files as it's more efficient than bzip2.
=> Prefer xz compression program when compressing sa data files

configure.in
Different architectures have different format of /proc/cpuinfo and also, only
i386 and x86_64 archs support cpu flags. Using "getconf LONG_BIT" command it's
possible to detect 64 bit OS on multiple different architectures. This patch was
successfully tested on i386, x86_64, s390x, ppc64 and aarch64 archs.
=> Portable way to detect 64 bit OS in configure script

man/sadf.in, man/sar.in, sa_common.c, sadf.c, sar.c
This achieves a level of consistency with the other platforms (e.g. Solaris and AIX) where their sar commands support hh:mm.
(New pull request, without the NLS files)
=> Permit times passed from command line to be in hh:mm as well as hh:mm:ss  

Makefile.in, configure.in
This pull request fixes 2 issues:
* when using --enable-install-cron option with configure, and DESTDIR is not empty, some required directories are missing in the DESTDIR, and this can negatively affects installation of systemd or cron files. Commit included in this pull request creates required directories according to their existence outside of DESTDIR.
* there were issues with --enable-install-cron configure option when used on systems without systemd. This should be also fixed.
Last commit slightly modifies checking for programs in configure script: don't look for programs in weird places - if they don't exist within PATH, they are unusable anyway. Also don't pretend that programs exist on the system if they are not found (AC_CHECK_PROG(S) have slightly different arguments compared to …
=> Fixes for installation of systemd / cron files

man/sar.in, pr_stats.c, rd_stats.c, rd_stats.h, sa.h, sa_common.c, sar.c
Add option to show mountpoint names instead of filesystem device, via "sar -F MOUNT".  Useful when some crazy fool has used generic LV names.
Existing output as below:
$ ./sadc -S XALL 1 2 /tmp/foo
$ ./sar -F -f /tmp/foo
Linux 3.18.7-100.fc20.x86_64 (localhost.localdomain)    03/13/2015      _x86_64_        (2 CPU)
12:33:27 PM  MBfsfree  MBfsused   %fsused  %ufsused     Ifree     Iused    %Iused FILESYSTEM
12:33:28 PM      6859     10857     61.28     66.49    901972    259020     22.31 /dev/sda5
12:33:28 PM       170       113     39.88     46.61     76592       320      0.42 /dev/sda2
12:33:28 PM        19         0      0.87      6.03      5125        11      0.21 /dev/mapper/foo-lv1
12:33:28 PM        19         0      0.87      6.03      5125        11      0.21 /dev/mapper/foo-lv2 …
=> Add option to display mountpoint names instead of filesystem names.

json_stats.c
When sadf used to produce JSON format, parse "-F MOUNT" correctly, to show mountpoints rather than filesystems.
=> Mountpoint json

xml_stats.c
When sadf used to produce XML format, parse "-F MOUNT" correctly, to show mountpoints rather than filesystems.
=> xml output with support for -F MOUNT

sa2.in
For people logging every 1 min, generating the summary at 23:53 is not good
enough: 7 minutes of data points are lost. What is needed is to generate
the summary early in the next day. In order to generate yesterday's
summary without recompiling you can now add the following line in config:
YESTERDAY="--date=yesterday"
=> YESTERDAY variable can now be changed in the generic configuration file.

build/yesterday, configure, configure.in, cron/crontab.sample, cron/sysstat-summary.timer.in, cron/sysstat.crond.in, iconfig, sa2.in, sysstat.sysconfig.in
This can be overriden by setting YESTERDAY=no in the configuration.
The compile time option was removed to make it clear that this is
controlled in one place, which also led to to logic simplification
and code removal.
This change fixes the following issues:
* Previously summary was being generated at 23:53, which caused up to 7
datapoints lost if sa1 logging was set to 1 or 5 minute intervals.
* To amend the previous problem, some distributions were compiling with
YESTERDAY set as a compile-time option, but shipped the cron jobs
as-is. This caused the additional issue that the report of a day was being
delayed up to 23:53 of the next day.
* Finally there is a subtle race condition that might happen if sadc tries to
write to the file while sar is reading it to generate the summary, which …
=> By default sa2 now generates summary for YESTERDAY

activity.c, common.h, json_stats.c, json_stats.h, man/sar.in, pr_stats.c, pr_stats.h, rd_stats.c, rd_stats.h, rndr_stats.c, rndr_stats.h, sa.h, sa_common.c, sa_wrap.c, sar.c, xml_stats.c, xml_stats.h
Disk I/O is often a bottleneck, so to supplement the existing "sar -d" reporting, the reporting of Fibre Channel HBA statistics is added.
New "sar" man page section reads as below:
With the FC keyword, statistics about fibre channel traffic are reported.  Note that fibre channel statistics depend on sadc's option "-S DISK" to be collected.  The following values are displayed:
FCHBA
Name of the fibre channel host bus adapter (HBA) interface for which statistics are reported.
hba_rxf/s
The total number of frames received per second.
hba_txf/s
The total number of frames transmitted per second.
hba_rxw/s
The total number of words received per second.
hba_txw/s
The total number of words transmitted per second.
Typical example usage:
$ ./sar -n FC -f /var/tmp/skfoo
Linux 3.18.7-100.fc20.x86_64 …
=> Fibre Channel HBA activity reporting

contrib/isag/isag.in
There is a race condition in sysstat that
sometimes causes it to record events that
happen at 23:59:59 as if they actually happened at 00:00:00 and
they end up in the report for the wrong day.
This change prevents isag from choking on the bug.
=> Worked around a race condition in sysstat.

pidstat.c, pidstat.h
On systems with many short living processes pidstat could run out of
pre-allocated space for PIDs. This patch increases NR_PID_PREALLOC constant so
more space for PIDs is pre-allocated, but also adds possibility to re-allocate
this space if needed.
Resolves #73
=> Pidstat outputs values > 100% for %CPU

contrib/sargraph/sargraph2
bread/s returns blocks so assuming 512bytes per block:
MB = bread * 512 / 1024 / 1024 = bread / 2 / 1024
not
MB = bread * 2 / 1024
=> sagraph2: fix MB/s units and help typo

common.h
We hit current limit of 2048 CPUs defined in common.h. Kernel upstream has
currently set 8192 as maximum number of CPUs[1], so sync with them.
[1] http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=b53b5eda8194214928c8243d711a75dbf51809fc
=> Increase NR_CPUS to match kernel upstream

common.c, common.h, man/sar.in, sar.c
sar command prints the date in the header in the ISO 8601 format (YYYY-MM-DD) when environment variable S_TIME_FORMAT is "ISO". Even with the configuration, the time printed with stats is still locale depended.
```
Linux 3.10.0-327.el7.x86_64 (host.example.com)       2016-02-24      _x86_64_
(48 CPU)
00時00分01秒     CPU     %user     %nice   %system   %iowait    %steal     %idle
00時10分01秒     all      0.32      0.00      0.13      0.01      0.00     99.54
...
```
With this patch, the time is also printed in the ISO format:
```
Linux 3.10.0-327.el7.x86_64 (host.example.com)       2016-02-24      _x86_64_
(48 CPU)
14:25:17        CPU     %user     %nice   %system   %iowait    %steal     %idle
14:25:52        all      1.77      0.00      0.36      0.01      0.00     97.85
...
```
=> Print time in the ISO format if S_TIME_FORMAT=ISO in sar

sadf_misc.c
Fixes minor typo in sadf_misc.c, where `text-anchror` is generated rather than `text-anchor`.
=> typo text-anchror -> text-anchor

svg_stats.c
html file generated for SVG would read
<text x=-10 y="30"
instead of
<text x="-10" y="30"
=> Fixes minor typo where attribute value was not surrounded by quotes

common.h, pidstat.c
Under specific loads, pidstat can output values bigger than 100% in CPU
statistics caused by inaccurate read of statistics provided by kernel.
This patch adds new SP_VALUE_100() macro which limits value to 100 for these
statistics, so the output can be correctly interpreted.
=> Introduce new SP_VALUE_100() macro and use it in pidstat

pidstat.c, pr_stats.c
Fixes #108.
This may not be a complete fix, but it at least highlights all the areas that I could find where a cast is necessary.
=> Quick fix for cprintf_u64 non-uintv64_t

sa.h, sa_common.c
The file_magic->header_size should never be outside of the boundary set by
MIN_FILE_HEADER_SIZE and MAX_FILE_HEADER_SIZE.
Should resolve coverity CID 29717 and CID 29719.
=> Stricter check for file_magic->header_size

sa.h, sar.c
On systems that use Korean UTF-8 locale sar will not print timestamp
because there is not enough space in the buffer.
I bumped buffer size to 64 bytes because I figured out that 32 bytes is
still not enough to print out timestamp when using some glibc supported
locales.
```
$ LC_TIME=ko_KR.UTF-8 ./sar 1 1
```
Before:
```
Linux 4.7.2-201.fc24.x86_64 (morgoth.usersys.redhat.com)        2016년 09월 30일   _x86_64_        (4 CPU)
CPU     %user     %nice   %system   %iowait    %steal     %idle
all      4.51      0.00      2.51      0.00      0.00     92.98
Average:        all      4.51      0.00      2.51      0.00      0.00     92.98
```
After:
```
Linux 4.7.2-201.fc24.x86_64 (morgoth.usersys.redhat.com)   2016년 09월 30일   _x86_64_        (4 CPU)
18시 18분 36초     CPU     %user     %nice   %system …
```
=> sar: make buffers that hold timestamps bigger

rd_stats.c
Currently CPU frequency is not being read properly on POWER archicture.
It shows the frequency as:
...
06:30:28 AM     CPU       MHz
06:30:36 AM     all      0.00
This is caused because /proc/cpuinfo is differently between Intel and
POWER.
This patch simply fix the parsing function (read_cpuinfo).
Signed-off-by: Breno Leitao <breno.leitao@gmail.com>
=> sar: Improve cpuinfo read for POWER architecture

man/pidstat.1, pidstat.c, pidstat.h
%wait: percentage of CPU spent by the task while waiting to run
The time waiting to run reflects how nicely some process was treated by the scheduler, we may refer to this info to do some priority adjustments or to distribute more cpu resources to those key processes
=> Add %wait to pidstat

common.c
Since 33557c3d: Display a percent sign after the value when --human
option used in non --human mode the output has an exta spurious '0'
byte.
That is printed by the percentage unit being set to char u = '\0'.
But that is not "nothing" it is literally byte "00".
This change only calls printf with a literal % when needed.
Fixes 165
Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>
=> fix 00 byte after values when --human is not set

.lgtm.yml
Salut Sebastien
As promised, the configuration file that will exclude the contrib directory from the evaluation
=> Configure LGTM to exclude python code: declare as docs

tests/0230
Best I can tell, it's been a good while since `sadf` last produced malformatted JSON (`v11.2.0`, Dec 2015), so, awesome!
Looking at the CI tests, any thoughts on including a test for validating the format of `sadf`'s JSON?
This pull request includes an example of a test that covers all of my practical use-cases. 
Similar to `tests/0104`, but using `json_pp` to validate the resulting JSON.  I picked `json_pp` because it comes standard with Perl.
=> Add a JSON parse test

FAQ.md, cron/crontab.sample, cron/sysstat.cron.daily.in, cron/sysstat.cron.hourly.in, cron/sysstat.crond.in, man/sa2.in
Crontab entries within sysstat in some cases make use of "&" to background the job.  Use of "&" is not required and is therefore irrelevant and only serves to introduce a degree of inconsistency.  See typical example below, where an install has create an example entry referencing "&" but an actual entry lacking it.
Example
[root@localhost ~]# grep sa1 /etc/cron.d/sysstat
*/10 * * * * root /usr/lib64/sa/sa1 1 1
[root@localhost ~]#
This PR removes use of "&" from code, from man pages and from the FAQ.
=> remove superfluous '&' within crontabs

sar.c
file_hdr is used to report number of CPUs
Signed-off-by: Anatoly Pugachev <matorola@gmail.com>
=> sar: fix a small inconsistency in header of print_sar_restart function

rd_stats.c
`memcpy` appears to be a popular way to overcome this newly introduced warning from GCC 8.
=> Use memcpy rather than strncpy, in order to avoid truncation warning

man/sadc.in, sa.h, sadc.c
For quite some time, the sadc utility has not used fdatasync() when writing
stat information to disk. This resulted in instances where data files could
be corrupted or entries lost if a system encountered a sudden reset
condition. This change adds a "-f" flag which can be used to bring back the
previous behaviour if end users require it.
Note, the fdatasync() lowers the likelihood of lost data, but does so at
the expense of performance within the write operation.
=> sadc: Add a -f flag to force fdatasync() use

mpstat.c
When mpstat is stopped by SIGINT, the JSON output will miss the
trailing "}" and "]" because SIGINT handler isn't called.  Fixed this
via setup SIGINT handler for JSON output too.
=> Fix missing "}" and "]" in JSON output when stopped by SIGINT

sa1.in, sa2.in, sysstat.sysconfig.in
- Added sysconfig variable UMASK=0022 with by default the current umask value
- Updated sa1 and sa2 to use the UMASK variable, just after the sysconfig file is sourced.
- Added a default UMASK variable in sa1 and sa2 to support absence of the new variable in the sysconfig file
=> #217: add umask sysconfig variable for sa1 and sa2

rd_stats.c, tests/expected.sadf-r
In 789cd86fb0, read_net_icmp() obtained code to differentiate between
the old and new format of /proc/net/snmp, which differ by the addition
of "InCsumErrors" in the 3rd position. Add the exact same handling logic
to read_net_eicmp() as well
Signed-off-by: Alexandros Kosiaris <akosiaris@gmail.com>
=> Check for InCsumErrors for EICMP as well

FAQ.md
A very minor improvement. The github markdown interprets the `---` directly after the backticks correctly, but other markdown interpreters see it as an indication for a new section.
Problem can be overcome by an empty line and is also consistent with the other usages in the FAQ.md
=> Missing empty line

common.c, ioconf.c, sa_common.c
These are from Alpine Linux (which uses musl libc by default)
=> add missing includes for musl

iostat.c, iostat.h, man/iostat.in
Statistics for flush operations have been added into Linux 5.5
Signed-off-by: Konstantin Khlebnikov <khlebnikov@yandex-team.ru>
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b6866318657717c8914673a6394894d12bc9ff5e
Fixes #240
=> iostat: Add flush I/O statistics

sa2.in
Fix `sa2` script, so it wont complain about "unrecognized archive format" on empty list for compress program.
if last find (in sa2 shell script), wont find any files
```
find "${SA_DIR}" -type f -mtime +${COMPRESSAFTER} \
| egrep "${UNCOMPRESSED_SAFILES_REGEX}" \
| xargs  "${ZIP}" > /dev/null
```
there would be a warning produced:
```
...
+ UNCOMPRESSED_SAFILES_REGEX='/sar?[0-9]{2,8}$'
+ find /var/log/sysstat -type f -mtime +10
+ egrep '/sar?[0-9]{2,8}$'
+ xargs pixz
Unrecognized archive format
Error reading archive entry
+ exit 0
```
(and mail is sent , if run from cron via /etc/cron.daily/sysstat (in debian))
=> Fix sa2 script, so it wont complain about "unrecognized archive format"

Makefile.in, configure.in
Some libc implementations like uclibc or musl provides
gettext stubs via libintl library. Without it, build will fail on:
```
/home/fabrice/buildroot/output/host/bin/arm-linux-gcc -o cifsiostat -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os   -Wall -Wstrict-prototypes -pipe -O2 cifsiostat.o librdstats_light.a libsyscom.a -s
/home/fabrice/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-musleabihf/8.3.0/../../../../arm-buildroot-linux-musleabihf/bin/ld: tapestat.o: in function `usage':
tapestat.c:(.text+0x44c): undefined reference to `libintl_gettext'
```
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> Link with -lintl if needed

sa1.in
The code `[ -d ${SA_DIR} ] || SA_DIR=@SA_DIR@` in `sa1.in`,  if  ${SA_DIR} doesn`t exist, we set SA_DIR=@SA_DIR@(/var/log/sa),  but /var/log/sa could be removed in some cases. Then sysstat will write system activity daily data in /var/log/sa as a file.
```
[root@localhost ~]# ll /var/log/sa
-rw-r--r--. 1 root root 304740 Apr 28 22:30 /var/log/sa
```
Now /var/log/sa is a file instead of a directory , but the sar command without a parameter will try to find a  system activity daily data file in /var/log/sa/ .
```
[root@localhost ~]# sar
Cannot open /var/log/sa/sa28: Not a directory
```
I think the directory @SA_DIR@ should always exist. We should judge if the directory exists  or not , and mkdir when the directory doesn`t exist.
=> sa1: fix sar error when the directory var/log/sa was removed.

common.c, tests/12.0.1/common.c
According to [glibc documentation][1], "index is another name for strchr; they are exactly the same. New code should always use strchr." The use of `index()` breaks compilation for Android targets, which use Bionic instead of glibc and don't have `index()`.
[1]: https://www.gnu.org/software/libc/manual/html_node/Search-Functions.html#index-index
=> Replace index() call with strchr() call

sar.c, tests/12.0.1/inisar.c
There is a small typo in sar.c, tests/12.0.1/inisar.c.
Should read `structures` rather than `stuctures`.
=> docs: fix simple typo, stuctures -> structures

pidstat.c
Do not set alarms for the undefined value of the interval. Also, allow to
print stats even if the SIGINT/SIGCHLD occurs before the first interval.
Hence, the command `pidstat -e <prog-name>`
will exec and monitor the prog-name process and show the PID stats after the
prog-name is completed its execution.
Signed-off-by: Parth Shah <parths1229@gmail.com>
=> pidstat: Monitor and show stats at the end of the exec program

pcp_def_metrics.c, pcp_def_metrics.h, pcp_stats.c, pcp_stats.h, sa.h, sadf.c, sadf_misc.c
When operating with the -l option in sadf we want to generate PCP
archives that match the PCP archives generated by pmlogger(1) as
closely as possible.  The advantage to doing this is that the live
and historical modes to the PCP tools become interchangeable; i.e.
pmchart views, pmie rules, grafana-pcp dashboards, and so on, all
expect metrics named according to the PCP conventions.
The reason sadf is not already doing this (AIUI), is that it was
originally based on the sar2pcp(1) utility.  This tool (which we
plan to deprecate in PCP in favour of the sysstat functionality)
used the rate-converted counter values as its starting point and
not the raw counters we have access to within sysstat itself.
I've audited all of the metrics being added to PCP archives with
the sadf -l option now, …
=> Update sadf to use metadata matching the same metrics from PCP

Makefile.in, contrib/sargraph/sargraph, contrib/sargraph/sargraph2, sa2.in
`egrep` has been deprecated in GNU grep since 2007, and in current post
3.7 Git it has been made to emit obsolescence warnings:
https://git.savannah.gnu.org/cgit/grep.git/commit/?id=a9515624709865d480e3142fd959bccd1c9372d1
=> *: use `grep -E` instead of `egrep`

pcp_def_metrics.c, pcp_stats.c, sa.h, sadf_misc.c
Use the PCP instance domain convention with kernel.percpu.interrupts
where the interrupt line and cpu ID are combined.  This provides the
same metric as PCP and also a single stable metric identifier (pmID).
Signed-off-by: Nathan Scott <nathans@redhat.com>
=> A_IRQ: sadf: Update PCP interface for per-CPU interrupts statistics

Makefile.in, configure, configure.in
The `configure` script help says that the `LDFLAGS` environment variable can be used to pass additional flags to linker during build.
However, `Makefile.in` did not mention this variable at all so the additional flags were silently skipped.
=> Honour `LDFLAGS` passed to `./configure`

sa_common.c, sadf.c, sadf_misc.c, svg_stats.c
On platforms with 32-bit time_t, code up converts it to a 64-bit data
type.  The pointer to this 64-bit value is incorrectly passed to
a few functions that accept a pointer to a 32-bit time_t.
On little endian platforms the original 32-bit time_t value will be visible
this way but on big endian platforms only zeros will be seen and time
will be show as wrong values.
Update code to convert to time_t to be compatible with 32-bit be
platforms.
=> Convert 64-bit time value to time_t as needed

Makefile.in
Declare `sadc` dependency on `libsyscom.a`
Without this patch, `make -j1` would try to link `sadc`
and fail to find `libsyscom.a`
Fixes #329
=> Declare sadc dependency on libsyscom.a

README.md
It's a really minor thing, but the two commands provided in the README:
```sh
$ sudo systemctl enable sysstat
$ sudo systemctl start sysstat
```
can be written as a single command using the `systemctl enable --now` flag. This PR updates the README commands accordingly.
=> README: consolidate systemctl commands

man/sar.in, sar.c
Hi, this is no big contribution and I hope it is correct. I was a bit confused, when I tried the example from the man-page and it did not work. If I understand it correctly `-I 14` is not supported. Feel free to squash this into any cleanup commit :)
=> doc-fix: remove `-I int_list` from man-page and help.

man/mpstat.1, mpstat.c, mpstat.h
This is for fixing following issue :
Fixes https://github.com/sysstat/sysstat/issues/327
By introducing a -H option, we can also detect and display stats of physically hotplug CPUs, which could occur especially in virtual machines/ environments.
Tests:
Create a VM using virsh and run mpstat with an interval inside it.
`virsh setvcpus vm1 5 --live --config`
Before:
[root@localhost sysstat]# ./mpstat -P ALL 5
Linux 5.4.17-2136.310.7.1.el8uek.x86_64 (localhost.localdomain)         09/15/2022      _x86_64_        (2 CPU)
06:36:17 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
06:36:22 PM  all    0.10    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   99.90
06:36:22 PM    0    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00 …
=> Display physical hotplug vCPU stats

mpstat.c
Previous commits removed the usage of return value from rw_mpstat_loop().
Hence change return value from int to void again
Signed-off-by: Shaleen Bathla <shaleen.bathla@oracle.com>
=> mpstat: return void from rw_mpstat_loop

sadf_misc.c
A recent commit change the format string in the snprintf function call on line 835 of sadf_misc.c, adding a space between the time and time zone in the output. In cases where there is no time zone to print, or if outputting epoch time with the -U option, there is trailing whitespace after the timestamp. This does not look nice, and can cause issues with parsers not expecting the whitespace.
This patch checks whether or not a time zone will be printed, and chooses the proper format accordingly.
=> Fix extra space when no TZ printed

cifsiostat.c, iostat.c, mpstat.c, pidstat.c, sar.c
Right now the argument of `--dec` is passed to `atoi(3)` which returns `0` on conversion error.  Therefore, `--dec=A` was not rejected and was equivalent to `--dec=0` by mistake.
=> Tools that take `--dec=X` option should only accept digits

pcp_def_metrics.c, pcp_stats.c
Fixed wrong indoms of PSI metrics
Fixed wrong data types for "pressure.*.full.total" metrics
Resolves https://github.com/sysstat/sysstat/issues/357
=> Fixed export of PSI metrics to a PCP archive

configure.ac
An autoconf generated script is designed to work with POSIX sh, and contains a /bin/sh shebang. As a result, it *cannot* assume it will be run with bash, as it won't be.
POSIX sh provides no way to extend the contents of a variable. A bash-specific extension is to use the += notation.
Instead, the standard (albeit somewhat more wordy) POSIX compatible approach is to expand the previous contents into a regular assignment. Do so.
Fixes: https://bugs.gentoo.org/923989
```
* QA Notice: Abnormal configure code
* 
* ./configure: 4927: CFLAGS+= -m32: not found
```
=> configure.ac: fix erroneous bashisms

pidstat.c
The value of %usr overflows and prints a bogus value when CPU user value was less than CPU guest value.
=> pidstat: Fix bogus %usr values in pidstat output.

sa_common.c, sadf_misc.c
Previously (#247) was rejected since sysstat is strictly for Linux, yet I found it very useful to be able to process `sa` binary data files on my mac laptop.  The changes are so simple that I created this branch for myself to be able to compile `sadf` (at least) and use it.  It works flawlessly.
Even if this PR is not accepted, this branch is easy enough to keep around and rebase as needed.
=> Slight changes to compile on Mac OS X

Makefile.in
This PR fixes an issue in the Makefile. Specifically, previously, any modifications of files like systest.h would not trigger a rebuild of common_light.o. The PR fixes this by including them as additional dependencies.
=> fixing missing dependencies in Makefile.in
